### ISSUE TITLE
docker-compose_default.yaml not working

### ISSUE THREAD

**Issue by huntertran** [DescartesResearch/TeaStore#139]
I tried to setup services using .yaml files in examples\docker\docker-compose_default.yaml, but the services are not connected

`Docker version 19.03.5`

**Comment by kasokz** [comment]
Hi,
I just ran it after cloning the repository and running `docker-compose -f examples/docker/docker-compose_default.yaml up` and it works fine on my machine.
I also have `Docker version 19.03.5, build 633a0ea`.
How did you run the example?
Does it say `Creating network "docker_default" with the default driver` or something similar?
All the services are put into that same network so they can communicate through the service names.
Can you check with `docker network inspect docker_default` (or whatever the created network was named) if all the services are inside that network?

**Comment by huntertran** [comment]
this is the result I've got:
```s
Creating network "docker_default" with the default driver
Creating docker_auth_1        ... done
Creating docker_webui_1       ... done
Creating docker_registry_1    ... done
Creating docker_persistence_1 ... done
Creating docker_image_1       ... done
Creating docker_recommender_1 ... done
Creating docker_db_1          ... done
```

The status in webui look like this
![image](https://user-images.githubusercontent.com/4468525/75389638-d9397380-58b4-11ea-8e51-c5c53dd9e722.png)

The network `docker_default` contains all the containers

I'm using Docker for Desktop on Windows with Linux container

Thank you for your help

**Comment by SimonEismann** [comment]
Hi Tuan,

I also attempted to recreate this issue and unfortunately was not able to. Can you run docker-compose without the `-d` flag and upload the full logs?

In the meantime, could you test the following docker-compose file that uses version 1.3.3 of `teastore-db`, as the MariaDB version used in 1.3.4. has been causing issues for some people. Let me know if this works for you.

```
version: '3'
services:
  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
  db:
    image: descartesresearch/teastore-db:1.3.3
    expose:
      - "3306"
    ports:
      - "3306:3306"
  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"
  auth:
    image: descartesresearch/teastore-auth
    expose:
      - "8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"
  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"
  recommender:
    image: descartesresearch/teastore-recommender
    expose:
      - "8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"
  webui:
    image: descartesresearch/teastore-webui
    expose:
      - "8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"
    ports:
      - "8080:8080"
```
